---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulscalerservice-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulscalerservice-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulscalerservice-rolebinding
subjects:
  - kind: ServiceAccount
    name: statefulscalerservice-account
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: statefulscalerservice-role
  apiGroup: rbac.authorization.k8s.io
---

